### PR TITLE
[fix] ownership and permissions on conf files

### LINKED ISSUE #703: Owner of /etc/rabbitmq
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: any
- Ruby: any
- Distribution: Gentoo
- Module version: Latest

## How to reproduce (e.g Puppet code you use)

Default code.

## What are you seeing

Wrong permissions on /etc/rabbitmq or NOT forced.

## What behaviour did you expect instead

Permissions of /etc/rabbitmq should be force to be owned by `$rabbitmq_user`. Because, it's required by : `/usr/sbin/rabbitmq-plugins enable rabbitmq_management` which creates `enabled_plugins` file in config dir under rabbitmq_user.

## Output log

```
 # /usr/sbin/rabbitmq-plugins enable rabbitmq_management
Error: {cannot_read_en
```

### LINKED ISSUE #813: breaks /etc/rabbitmq ownership under ubuntu
Puppet: 5.4.0
    Ruby: 2.5.1
    Distribution: Ubuntu 18.04
    Module version: 9.1.0

I found that the puppet-rabbitmq does not work when used repeatedly under Ubuntu, since puppet-rabbitmq changes the ownership of /etc/rabbitmq to root, while under Ubuntu (although I agree that this is poor design) it is supposed to be rabbitmq.rabbitmq, since rabbitmq-plugins want's to write /etc/rabbitmq/enabled_plugins and needs to temporarily create /etc/rabbitmq/enabled_plugins.tmp, therefore needs write access to /etc/rabbitmq.

### PR DESCRIPTION
**Pull request by wyardley**
#### Pull Request (PR) description
* Set owner of config directories to rabbitmq user rather than root
* Set group of config directories explicitly to rabbitmq, and set setgid bit
* Set more restrictive permissions on the SSL directory
* Update expectations, and test file permissions in acceptance tests

This is a narrower version of #796 (@dhoppe)
This does have some security implications, since when the file is owned by root, if the application is compromised, the rabbitmq user still may not be able to modify configuration files; with these changes, it would.

I _believe_ that changing the ownership this way should be safe even on older RabbitMQ versions. However, would appreciate some eyes and / or actual testing of this, as I'm not in a good position to do extensive validations beyond the acceptance tests.

#### This Pull Request (PR) fixes the following issues
Fixes #703
Closes #796
Fixes #813

### CODE REVIEW

File: spec/acceptance/class_spec.rb [hunk 1]
```diff
@@ -37,6 +37,19 @@ class { 'erlang': epel_enable => true}
       it { is_expected.to be_enabled }
       it { is_expected.to be_running }
     end
+
+    describe file('/etc/rabbitmq') do
+      it { is_expected.to be_directory }
+      it { is_expected.to be_owned_by 'rabbitmq' }
+      it { is_expected.to be_grouped_into 'rabbitmq' }
+    end
```
Comment (wyardley) [inline spec/acceptance/class_spec.rb:45]: _think_ this is the right place for these to live?
seems sensible to test these in the acceptance tests one way or another, I think, right?
