### PR TITLE
Fix issue #832 - removing federation upstream

### LINKED ISSUE #832: Problem removing (ensure => 'absent') federation upstream
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: puppet-agent 5.5.19-1stretch
- Ruby: ruby 1:2.3.3
- Distribution: debian stretch
- Module version: Version 10.0.0 of https://forge.puppet.com/puppet/rabbitmq

## How to reproduce (e.g Puppet code you use)
1. create federation upstream (ensure: present) ... upstream gets created:
```
rabbitmq_parameter { 'nonprod_settlement_develop@/develop':
  component_name => 'federation-upstream',
  ensure => 'present',
  value => {
    'uri' => 'amqps://fed_user:fed_pass@upstream_server:5672/%2fdevelop',
    'ack-mode' => 'on-confirm',
    'max-hops' => '10',
    'trust-user-id' => false,
  },
}
```
2. remove federation upstream (ensure: absent) ... you receive error removing inexistent shovel:
```
rabbitmq_parameter { 'nonprod_settlement_develop@/develop':
  component_name => 'federation-upstream',
  ensure => 'absent',
  value => {
    'uri' => 'amqps://fed_user:fed_pass@upstream_server:5672/%2fdevelop',
    'ack-mode' => 'on-confirm',
    'max-hops' => '10',
    'trust-user-id' => false,
  },
}
```

## What are you seeing
It looks like the removal operation tries to remove **shovel** instead of federation upstream.

## What behaviour did you expect instead
I expected federation upstream named 'nonprod_settlement_develop' inside vhost '/develop' to be removed from RabbitMQ cluster... and not observing an attempt to remove shovel with the same name inside the same vhost.

## Output log
Error: Execution of '/usr/sbin/rabbitmqctl clear_parameter -p /develop shovel nonprod_settlement_develop' returned 69: Clearing runtime parameter "nonprod_settlement_develop" for component "shovel" on vhost "/develop" ...
Error:
Parameter does not exist
Error: /Stage[main]/Messagebroker::Rabbitmq/Rabbitmq_parameter[nonprod_settlement_develop@/develop]/ensure: change from 'present' to 'absent' failed: Execution of '/usr/sbin/rabbitmqctl clear_parameter -p /develop shovel nonprod_settlement_develop' returned 69: Clearing runtime parameter "nonprod_settlement_develop" for component "shovel" on vhost "/develop" ...
Error:
Parameter does not exist

## Any additional information you'd like to impart
I have not one shovel defined anywhere. We use RabbitMQ 3.8.3 with Erlang 22.0.7.

### PR DESCRIPTION
**Pull request by fiksn**
#### Pull Request (PR) description

I just fixed the bug, there should be some better unit test as well.

#### This Pull Request (PR) fixes the following issues

Fixes #832

### CODE REVIEW

**Comment by bastelfreak** [comment]
@fiksn thanks for fixing this, can you somehow add a test to ensure this works now as expected?

**Comment by fiksn** [comment]
@bastelfreak: Yeah, adding tests would be my wish too, but unfortunately I am not that fluent with Ruby (yet). For now the test on my side is referencing my repo with the change in Puppetfile.

**Comment by fiksn** [comment]
I've added some unit tests and ran the stuff with `docker build .` It fails with the old version of code and passes with the new. So I suppose it should be good enough 🙂

**Comment by wyardley** [comment]
First glance, LGTM, but haven’t been doing much Puppet or Ruby development recently, so probably good to get some eyes on it, especially in terms of whether the tests test the right things.

File: Dockerfile [hunk 1]
```diff
@@ -1,6 +1,7 @@
 FROM ruby:2.5.3
 
 WORKDIR /opt/puppet
+ENV LC_ALL=C.UTF-8
```
Comment (wyardley) [inline Dockerfile:4]: Is this needed or just a byproduct of something you added for testing locally? Not sure if this file comes from modulesync

File: spec/unit/puppet/provider/rabbitmq_parameter/rabbitmqctl_federation_spec.rb [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+    described_class.instance_variable_set(:@parameters, nil)
+  end
+
+  describe '#prefetch' do
+    it 'exists' do
+      expect(described_class).to respond_to :prefetch
+    end
+
+    it 'matches' do
+      provider_class.expects(:rabbitmqctl_list).with('vhosts').returns <<-EOT
```
Comment (ekohl) [inline spec/unit/puppet/provider/rabbitmq_parameter/rabbitmqctl_federation_spec.rb:27]: In our modules we've been moving away from setting `expects` before the test but rather use `allow()`, then the test and then `expect().to have_received()`.
https://relishapp.com/rspec/rspec-mocks/docs/basics/spies#spy-on-a-method-on-a-partial-double

Comment (wyardley) [reply spec/unit/puppet/provider/rabbitmq_parameter/rabbitmqctl_federation_spec.rb:27]: Makes sense; given that the submitter said they’re not very experienced with tests, and that this matches the style of the rest of the tests, I’m inclined to say let’s accept this, and then someone can refactor the tests to the newer style later if it makes sense?

Comment (ekohl) [reply spec/unit/puppet/provider/rabbitmq_parameter/rabbitmqctl_federation_spec.rb:27]: I'm fine with that.

File: Dockerfile (hunk 1 above)
Comment (fiksn) [reply Dockerfile:4]: Apparently the default locale is set to "POSIX" and when I run the test through docker container rake fails with "ArgumentError: invalid byte sequence in US-ASCII". I agree that this might be a bit offtopic for this issue, but fact is that without that line `docker build .` fails. Of course if I installed and ran everything locally stuff still passes.

Not sure what should be done here. Perhaps I can squash my two commits that deal with this bug and then create a separate commit / pull request for the issue that test failure when using docker. Perhaps there is even some nicer way (like that it is expected to pass some -e LC_ALL.. flag, but didn't find any documentation about it).

**Comment by fiksn** [comment]
I am more than happy to contribute. Sorry for not being responsive lately.

Removed the part from Dockerfile now and squashed the two commits (fix and unit tests). Passing environment variables won't work as easy as I thought since this is the "build" and not "run" phase (you can just add --build-arg). Do you believe it makes sense to open another issue for that one-liner?

**Comment by wyardley** [comment]
@fiksn so, I'm not doing too much work on Vox modules anymore, but the `Dockerfile` comes from https://github.com/voxpupuli/modulesync_config, so we can't make modifications directly to it in this module vs. upstream.

We have seen a few issues with locale settings like `LANG` or `LC_ALL` in this module, and there are some existing workarounds (e.g., 6c7a1467370ac926b48d6aa3c7aed4a78301b175) related to the CLI tools needing those to be set. These issues would only come up on systems where it wasn't set system-wide, so this may be a similar kind of issue.

It may be that more of those need to be made, vs. adjusting the environment in the test env, as this could actually be reflecting a real problem in cases where that env isn't set at system level. As the tests work in CI, I think we can assume the module is working, for the most part.
